In [9]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [10]:
#2. Print the NUMPY version and the configuration.
np.version.version

'1.16.2'

In [11]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a = np.random.random((2,3,5))

In [12]:
#4. Print a.
print(a)

[[[0.51052969 0.11731672 0.25153278 0.49856898 0.00655309]
  [0.21921218 0.7443088  0.91498524 0.18468176 0.56731871]
  [0.57376421 0.52247525 0.53290897 0.41252615 0.26644179]]

 [[0.1103046  0.3278303  0.90065169 0.4303667  0.60812309]
  [0.80696226 0.09284797 0.64477335 0.3785811  0.83111785]
  [0.02154797 0.30310328 0.74878065 0.48442457 0.75985018]]]


In [13]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.ones((5,2,3))

In [14]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [15]:
#7. Do a and b have the same size? How do you prove that in Python code?
a.shape == b.shape

False

In [16]:
#8. Are you able to add a and b? Why or why not?
# print(np.add(a,b)) doesnt work because the 2 matrices doesnt have the same shape

In [17]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = np.transpose(b,(1,2,0))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [18]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = np.add(a,c)
print(d)

[[[1.51052969 1.11731672 1.25153278 1.49856898 1.00655309]
  [1.21921218 1.7443088  1.91498524 1.18468176 1.56731871]
  [1.57376421 1.52247525 1.53290897 1.41252615 1.26644179]]

 [[1.1103046  1.3278303  1.90065169 1.4303667  1.60812309]
  [1.80696226 1.09284797 1.64477335 1.3785811  1.83111785]
  [1.02154797 1.30310328 1.74878065 1.48442457 1.75985018]]]


In [19]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)

print(d)
#d is every values of a + 1

[[[0.51052969 0.11731672 0.25153278 0.49856898 0.00655309]
  [0.21921218 0.7443088  0.91498524 0.18468176 0.56731871]
  [0.57376421 0.52247525 0.53290897 0.41252615 0.26644179]]

 [[0.1103046  0.3278303  0.90065169 0.4303667  0.60812309]
  [0.80696226 0.09284797 0.64477335 0.3785811  0.83111785]
  [0.02154797 0.30310328 0.74878065 0.48442457 0.75985018]]]
[[[1.51052969 1.11731672 1.25153278 1.49856898 1.00655309]
  [1.21921218 1.7443088  1.91498524 1.18468176 1.56731871]
  [1.57376421 1.52247525 1.53290897 1.41252615 1.26644179]]

 [[1.1103046  1.3278303  1.90065169 1.4303667  1.60812309]
  [1.80696226 1.09284797 1.64477335 1.3785811  1.83111785]
  [1.02154797 1.30310328 1.74878065 1.48442457 1.75985018]]]


In [20]:
#12. Multiply a and c. Assign the result to e.
e = np.multiply(a,c)
e

array([[[0.51052969, 0.11731672, 0.25153278, 0.49856898, 0.00655309],
        [0.21921218, 0.7443088 , 0.91498524, 0.18468176, 0.56731871],
        [0.57376421, 0.52247525, 0.53290897, 0.41252615, 0.26644179]],

       [[0.1103046 , 0.3278303 , 0.90065169, 0.4303667 , 0.60812309],
        [0.80696226, 0.09284797, 0.64477335, 0.3785811 , 0.83111785],
        [0.02154797, 0.30310328, 0.74878065, 0.48442457, 0.75985018]]])

In [21]:
#13. Does e equal to a? Why or why not?
e == a
# It is equal because a*1=a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [22]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = np.max(d)
d_min = np.min(d)
d_mean= np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

1.9149852432151686
1.0065530922360684
1.4590796635136425


In [23]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f=np.empty((2,3,5))
f

array([[[0.51052969, 0.11731672, 0.25153278, 0.49856898, 0.00655309],
        [0.21921218, 0.7443088 , 0.91498524, 0.18468176, 0.56731871],
        [0.57376421, 0.52247525, 0.53290897, 0.41252615, 0.26644179]],

       [[0.1103046 , 0.3278303 , 0.90065169, 0.4303667 , 0.60812309],
        [0.80696226, 0.09284797, 0.64477335, 0.3785811 , 0.83111785],
        [0.02154797, 0.30310328, 0.74878065, 0.48442457, 0.75985018]]])

In [24]:
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
#If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
#If a value equals to d_mean, assign 50 to the corresponding value in f.
#Assign 0 to the corresponding value(s) in f for d_min in d.
#Assign 100 to the corresponding value(s) in f for d_max in d.
#In the end, f should have only the following values: 0, 25, 50, 75, and 100.
#Note: you don't have to use Numpy in this question.

In [25]:
f[(d>d_min) & (d<d_mean)]=25
f[(d>d_mean) & (d<d_max)]=75
f[d==d_mean]=50
f[d==d_min]=0
f[d==d_max]=100
f

array([[[ 75.,  25.,  25.,  75.,   0.],
        [ 25.,  75., 100.,  25.,  75.],
        [ 75.,  75.,  75.,  25.,  25.]],

       [[ 25.,  25.,  75.,  25.,  75.],
        [ 75.,  25.,  75.,  25.,  75.],
        [ 25.,  25.,  75.,  75.,  75.]]])

In [26]:
#17. Print d and f. Do you have your expected f?
#For instance, if your d is:
#array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
#        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
#        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
#
#       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
#        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
#        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])
#Your f should be:
#array([[[ 75.,  75.,  75.,  25.,  75.],
#        [ 75.,  75.,  25.,  25.,  25.],
#        [ 75.,  25.,  75.,  75.,  75.]],
#
#       [[ 25.,  25.,  25.,  25., 100.],
#        [ 75.,  75.,  75.,  75.,  75.],
#        [ 25.,  75.,   0.,  75.,  75.]]])

print(d)
print(f)


[[[1.51052969 1.11731672 1.25153278 1.49856898 1.00655309]
  [1.21921218 1.7443088  1.91498524 1.18468176 1.56731871]
  [1.57376421 1.52247525 1.53290897 1.41252615 1.26644179]]

 [[1.1103046  1.3278303  1.90065169 1.4303667  1.60812309]
  [1.80696226 1.09284797 1.64477335 1.3785811  1.83111785]
  [1.02154797 1.30310328 1.74878065 1.48442457 1.75985018]]]
[[[ 75.  25.  25.  75.   0.]
  [ 25.  75. 100.  25.  75.]
  [ 75.  75.  75.  25.  25.]]

 [[ 25.  25.  75.  25.  75.]
  [ 75.  25.  75.  25.  75.]
  [ 25.  25.  75.  75.  75.]]]


In [27]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
#("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
#array([[[ 'D',  'D',  'D',  'B',  'D'],
#        [ 'D',  'D',  'B',  'B',  'B'],
#        [ 'D',  'B',  'D',  'D',  'D']],
#
#       [[ 'B',  'B',  'B',  'B',  'E'],
#        [ 'D',  'D',  'D',  'D',  'D'],
#        [ 'B',  'D',   'A',  'D', 'D']]])
#Again, you don't need Numpy in this question.
## Corrections Selim :

def f_fun(d_min, d_max, d_mean, d):
    if  d_min < d < d_mean:
        f = "B"
    elif  d_mean < d < d_max :
        f = "D"
    elif d == d_mean :
        f= "C"
    elif d == d_min :
        f= "A"
    elif d == d_max :
        f = "E"
    return f

# python-function as ufunc
import numpy as np
vf= np.vectorize(lambda x :f_fun(d_min=d_min, d_max=d_max, d_mean=d_mean, d=x))
print(vf(d))

[[['D' 'B' 'B' 'D' 'A']
  ['B' 'D' 'E' 'B' 'D']
  ['D' 'D' 'D' 'B' 'B']]

 [['B' 'B' 'D' 'B' 'D']
  ['D' 'B' 'D' 'B' 'D']
  ['B' 'B' 'D' 'D' 'D']]]
