In [185]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [186]:
#2. Print the NUMPY version and the configuration.
np.version.version

'1.16.2'

In [187]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a = np.random.random((2,3,5))

In [188]:
#4. Print a.
print(a)

[[[0.3684122  0.28183177 0.72299683 0.06930666 0.18053568]
  [0.20625426 0.96116785 0.04349113 0.75043052 0.93610047]
  [0.85216325 0.62542055 0.44657232 0.9241116  0.86729076]]

 [[0.43602827 0.0956541  0.27758063 0.60847408 0.93265746]
  [0.77785265 0.08933309 0.0259857  0.65054658 0.2731168 ]
  [0.35873786 0.76537993 0.38597214 0.48227615 0.18098302]]]


In [189]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.ones((5,2,3))

In [190]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [191]:
#7. Do a and b have the same size? How do you prove that in Python code?
a.size == b.size

True

In [192]:
#8. Are you able to add a and b? Why or why not?
# print(np.add(a,b)) doesnt work because the 2 matrices doesnt have the same shape

In [193]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = np.transpose(b,(1,2,0))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [194]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = np.add(a,c)
print(d)

[[[1.3684122  1.28183177 1.72299683 1.06930666 1.18053568]
  [1.20625426 1.96116785 1.04349113 1.75043052 1.93610047]
  [1.85216325 1.62542055 1.44657232 1.9241116  1.86729076]]

 [[1.43602827 1.0956541  1.27758063 1.60847408 1.93265746]
  [1.77785265 1.08933309 1.0259857  1.65054658 1.2731168 ]
  [1.35873786 1.76537993 1.38597214 1.48227615 1.18098302]]]


In [195]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)

print(d)
#d is every values of a + 1

[[[0.3684122  0.28183177 0.72299683 0.06930666 0.18053568]
  [0.20625426 0.96116785 0.04349113 0.75043052 0.93610047]
  [0.85216325 0.62542055 0.44657232 0.9241116  0.86729076]]

 [[0.43602827 0.0956541  0.27758063 0.60847408 0.93265746]
  [0.77785265 0.08933309 0.0259857  0.65054658 0.2731168 ]
  [0.35873786 0.76537993 0.38597214 0.48227615 0.18098302]]]
[[[1.3684122  1.28183177 1.72299683 1.06930666 1.18053568]
  [1.20625426 1.96116785 1.04349113 1.75043052 1.93610047]
  [1.85216325 1.62542055 1.44657232 1.9241116  1.86729076]]

 [[1.43602827 1.0956541  1.27758063 1.60847408 1.93265746]
  [1.77785265 1.08933309 1.0259857  1.65054658 1.2731168 ]
  [1.35873786 1.76537993 1.38597214 1.48227615 1.18098302]]]


In [196]:
#12. Multiply a and c. Assign the result to e.
e = np.multiply(a,c)
e

array([[[0.3684122 , 0.28183177, 0.72299683, 0.06930666, 0.18053568],
        [0.20625426, 0.96116785, 0.04349113, 0.75043052, 0.93610047],
        [0.85216325, 0.62542055, 0.44657232, 0.9241116 , 0.86729076]],

       [[0.43602827, 0.0956541 , 0.27758063, 0.60847408, 0.93265746],
        [0.77785265, 0.08933309, 0.0259857 , 0.65054658, 0.2731168 ],
        [0.35873786, 0.76537993, 0.38597214, 0.48227615, 0.18098302]]])

In [197]:
#13. Does e equal to a? Why or why not?
e == a
# It is equal because a*1=a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [198]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = np.max(d)
d_min = np.min(d)
d_mean= np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

1.9611678475060703
1.0259856983320699
1.485888810124688


In [199]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.
f=np.empty((2,3,5))
f

array([[[0.3684122 , 0.28183177, 0.72299683, 0.06930666, 0.18053568],
        [0.20625426, 0.96116785, 0.04349113, 0.75043052, 0.93610047],
        [0.85216325, 0.62542055, 0.44657232, 0.9241116 , 0.86729076]],

       [[0.43602827, 0.0956541 , 0.27758063, 0.60847408, 0.93265746],
        [0.77785265, 0.08933309, 0.0259857 , 0.65054658, 0.2731168 ],
        [0.35873786, 0.76537993, 0.38597214, 0.48227615, 0.18098302]]])

In [200]:
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
#If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
#If a value equals to d_mean, assign 50 to the corresponding value in f.
#Assign 0 to the corresponding value(s) in f for d_min in d.
#Assign 100 to the corresponding value(s) in f for d_max in d.
#In the end, f should have only the following values: 0, 25, 50, 75, and 100.
#Note: you don't have to use Numpy in this question.

In [213]:
f[(d>d_min) & (d<d_mean)]=25
f[(d>d_mean) & (d<d_max)]=75
f[d==d_mean]=50
f[d==d_min]=0
f[d==d_max]=100
f

array([[[ 25.,  25.,  75.,  25.,  25.],
        [ 25., 100.,  25.,  75.,  75.],
        [ 75.,  75.,  25.,  75.,  75.]],

       [[ 25.,  25.,  25.,  75.,  75.],
        [ 75.,  25.,   0.,  75.,  25.],
        [ 25.,  75.,  25.,  25.,  25.]]])

In [214]:
#17. Print d and f. Do you have your expected f?
#For instance, if your d is:
#array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
#        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
#        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
#
#       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
#        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
#        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])
#Your f should be:
#array([[[ 75.,  75.,  75.,  25.,  75.],
#        [ 75.,  75.,  25.,  25.,  25.],
#        [ 75.,  25.,  75.,  75.,  75.]],
#
#       [[ 25.,  25.,  25.,  25., 100.],
#        [ 75.,  75.,  75.,  75.,  75.],
#        [ 25.,  75.,   0.,  75.,  75.]]])

print(d)
print(f)


[[[1.3684122  1.28183177 1.72299683 1.06930666 1.18053568]
  [1.20625426 1.96116785 1.04349113 1.75043052 1.93610047]
  [1.85216325 1.62542055 1.44657232 1.9241116  1.86729076]]

 [[1.43602827 1.0956541  1.27758063 1.60847408 1.93265746]
  [1.77785265 1.08933309 1.0259857  1.65054658 1.2731168 ]
  [1.35873786 1.76537993 1.38597214 1.48227615 1.18098302]]]
[[[ 25.  25.  75.  25.  25.]
  [ 25. 100.  25.  75.  75.]
  [ 75.  75.  25.  75.  75.]]

 [[ 25.  25.  25.  75.  75.]
  [ 75.  25.   0.  75.  25.]
  [ 25.  75.  25.  25.  25.]]]


In [219]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
#("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
#array([[[ 'D',  'D',  'D',  'B',  'D'],
#        [ 'D',  'D',  'B',  'B',  'B'],
#        [ 'D',  'B',  'D',  'D',  'D']],
#
#       [[ 'B',  'B',  'B',  'B',  'E'],
#        [ 'D',  'D',  'D',  'D',  'D'],
#        [ 'B',  'D',   'A',  'D', 'D']]])
#Again, you don't need Numpy in this question.